### ISSUE TITLE
September checklist

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#547]
- [ ] Search view with chembl data in it
- [ ] Make the required fields work (another array.map function)
- [ ] Export a chembl JSON
- [ ] Export an XLS file
- [x] Rework file cancellation
- [ ] Check for bugs in un-applying the search
