### ISSUE TITLE
testing checklist

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#846]
Welcome to the ChemBio Hub wiki!

ChemBio Hub provides a collection of tools for curating and analysing data.

ChemBio AssayReg

List of features for use in testing checklists

###App wide 
- [ ] Buttons for update, save, cancel and clear are appropriate across each user interface and are in the same order. Colours are meaningful
- [ ] ~~viewers cannot edit data in projects by using the add a compound, and an inventory item, add multiple compounds or add multiple inventory items~~
- [ ] editors can do everything that viewers can do
- [ ] There is no difference between being in a group that has editor/viewer permissions or being a user that has them
- [ ] inactive users cannot log on to the system either via sso or via password login
- [ ] a user can be invited, see the 4 scenarios outlined here: https://github.com/thesgc/chembiohub_helpdesk/issues/679
- [ ] password reset – if the password entered by a user is incorrect, the user gets a link to the password reset form, which works
- [ ] password change

###Project List  
- [ ] Project List lists all projects to which the user has access
- [ ] Compound search links
- [ ] Draw compound link should lead to something relevant
- [ ] Add single inventory item link should be relevant
- [ ] Assay Overview Link
- [ ] Project Type Icons
- [ ] Filter Project List
- [ ] Project List title
- [ ] If a project has no data form configs set up, it will not display assayreg options or the assayreg icon
- [ ] Project list info box
- [ ] Search box info box
- [ ] Add multiple inventory items
- [ ] Add single compound link from project page if >1 project selected should be disabled

###Compound Search 
- [ ] Compound preview after adding an upload
- [ ] Your saved items are shown below. You can now either view the full project or add more items.
- [ ] view full project
- [ ] Add multiple compound link from project page if >1 project selected should be disabled
- [ ] Add multiple if single inventory project selected should lead to add compounds page
- [ ] Add single if single invetory project selected should happen inline
- [ ] Add single should lead to the add single compound page if single compound project selected
- [ ] Add single inventory item link from project page
- [ ] Info box for edit mode
- [ ] edit mode edit a single field by click
- [ ] edit mode mark an item as archived
- [ ] edit mode with archive mode enabled from the search form allows archived items to be restored
- [ ] can fill down on archive/restore
- [ ] can fill  down with other fields
- [ ] after fill down a message appears and it is possible to undo the changes just made
- [ ] It is poissible to sort the search page
- [ ] It is possible to filter blanks or non blanks
- [ ] List display for chemreg shows 4 columns for project , user, structure etc and then shows project data fields and then date, batch and upload
- [ ] Custom fields in the handsontable consist of a unique list of the fields in the projects which have at that time been selected
- [ ] Links can be rendered appropriately if labelled as a link field
- [ ] Images can be rendered appropriately if labelled as an image link
- [ ] User can switch between gallery and list view
- [ ] User can search by keyword
- [ ] User can search by project data fields and the values they see are the most popular values in the data set that the current search is limitted to
- [ ] User can search by anything else in the search form
- [ ] Added by date is and inclusive data
- [ ] substructure or smarts search is highlighted in the images
- [ ] User can page through the results. If they then perform another action which changes the view then they get taken back to page 1. Likewise if they add an item
- [ ] Page, all search terms, archive mode, list or gallery choice, items per page are all retained when the page is reloaded by pressing ctrl f5
- [ ] Export gives the same number of results as the number in the data preview
- [ ] Show and hide search form works
- [ ] I can add a search term to the page from the top search bar and this is also reflected in the top of the table search bar
- [ ] If in another part of the app I can use the top search bar to redirect to a search of chemreg/invreg
- [ ] values from restricted fields should not be shown in the search dropdown

###Add single inventory item feature 
- [ ] Custom fields should be validated and required fields respected
- [ ] Should be possible to add uncurated fields
- [ ] Draw compound allows the user to draw and then validate a compound. If validation succesful then a save button is available
- [ ] Draw compound allows the user to draw and then validate a compound. If validation unsuccesful then relevant message is shown
- [ ] Draw compound allows the user save a compound and a relevant message is shown
- [ ] Custom fields can be added to the compound and are validated
- [ ] Existing values from that project are shown to the user as they add to an existing dropdown field
- [ ] Uncurated fields can be added individually

###Addcompounds 
- [ ] Add compounds info box
- [ ] Uploaded records info box
- [ ] With structures info box
- [ ] Without structures info box
- [ ] Overlaps info box
- [ ] What do the statuses mean?
- [ ] Appropriate message for unprocessable file
- [ ] Appropriate message for headers not retrieved
- [ ] Approriate message if saving the compounds fails
- [ ] Messages against individual compounds when uploaded correspond to appropriate error type
- [ ] Ability to sort the preview of compounds
- [ ] Ability to remove those sorts
- [ ] Ability to filter the preview of compounds by the different statuses
- [ ] Ability to remove those filters
- [ ] Ability to map a column to something in the custom fields
- [ ] Disabled mapping of a column if it doesn't fit in that datatype and message
- [ ] Ignoring data works by changing the dropdown. Message where saving the data changes to reflect this
- [ ] Ignored items are not saved
- [ ] Errors ignore by default but can be saved as new items if from xlsx
- [ ] Errors ignore by default but can be saved as new items if from sdf
- [ ] Errors ignore by default but CANNOT be saved as new items if from sdf
- [ ] Specific and different handling of SMILES mapping, not available if the file is an SDF
- [ ] Ability to do any of the above sorts and filters and then reload the page and get the same thing
- [ ] Custom fields are validated and required fields are respected in this process

###Admin 
- [ ] Custom field config can be compied and pasted to another copy of it
- [ ] After adding a new project the roles associated with that project appear in the multiselect for the permissions on the user and group pages
- [ ] After changing the data manager name and email in the skinning configuration these are reflected across the messages on the system
- [ ] File errors from backend, when selected results in the message from the backend error being displayed if there is an error on uploading the file
- [ ] Enable smiles input allows the smiles input on the add multiple page to be turned on or off
- [ ] Project alias, instance alias and result alias are reflected across the system
- [ ] show compounds toggles the display of compounds in assayreg and chemreg for that project and enables the copmpounds icon
- [ ] Project type name currently is not shown on the front end project list
- [ ] pinned custom fields shows only the custom fields that are generated for mapping fields to chembl
- [ ] custom field config list shows a mixture of those generated by adding assayreg tables and those generated manually
- [ ] project key and project name are changeable after creating the project
- [ ] default project does not do anything
- [ ] cbh plugins is an experimental half-working feature for adding calculated properties to compounds
- [ ] user or group permissions can be assigned in the admin area
- [ ] staff status users can log into the admin but only see and edit the items which they have been assigned permissions on in the user permissions select box
- [ ] superusers can change everything in the admin and have permissions for all projects
- [ ] If a decimal or number field is added to a custom field config this field should not be possible to add a string to on any of the following features: add single inventory, add multiple inventory, add multipl compound, add single compound, edit compound batch. It should also be the same across upload, edit and andd single on assayreg
- [ ] If a number field is added it should not be possible to add a decimal to it on any of the following features: add single inventory, add multiple inventory, add multipl compound, add single compound, edit compound batch. It should also be the same across upload, edit and andd single on assayreg
- [ ] If a percentage field is added it should validate to between 0 and 100 on any of the following features: add single inventory, add multiple inventory, add multipl compound, add single compound, edit compound batch. It should also be the same across upload, edit and andd single on assayreg
- [ ] If a choice field is added it should only be possible to add the allowed values or blank if the field is not required on any of the following features: add single inventory, add multiple inventory, add multipl compound, add single compound, edit compound batch. It should also be the same across upload, edit and andd single on assayreg
- [ ] If a date field is added then it should only be possible to add a date of the right format on any of the following features: add single inventory, add multiple inventory, add multipl compound, add single compound, edit compound batch. It should also be the same across upload, edit and andd single on assayreg
- [ ] abiguous date formats such as 09/01/01 should be interpretted as UK format by the file upload on assayreg and chemreg
- [ ] default values for fields should be interpretted correctly on  add single inventory, add multiple inventory, add multipl compound, add single compound, edit compound batch. It should also be the same across upload, edit and andd single on assayreg
- [ ] restricted fields should only be shown to editors
- [ ] Links can be rendered appropriately if labelled as a link field
- [ ] Images can be rendered appropriately if labelled as an image link
- [ ] The copy buttons on the single molecule view all work
- [ ] When I toggle edit mode I can edit the project data fields and the possible values choices returned are consistent with the project that the compound comes from. They also update when I add a value.
- [ ] The tag fields are consistent with the displayed tags when editing
- [ ] Searching for a tag to add is case insensitive but the tags that you do add are case sensitive
- [ ] There is a relevant message after updating a molecule
- [ ] After closing an updated molecule the list view updates
- [ ] Data is validated when editing a molecule

###AssayReg search 
- [ ] mapping to a chembl field should result in the right output on the assayreg search page
- [ ] custom field config data type should be shown on the assayreg front end on the data overview but is not shown on the assayreg search page for the different levels

**Comment by aekhendry** [comment]
When editing a project config, I cannot see the full name in a given field text box if the text is too long. This is quite irritating as I need to see this to know which fields I am editing. Also note that the Field type drop down looks messy as it is chopping the words up in awkward places.

In the project edit config view, the project types available need editing. All that is required is Chemical Inventory / Inventory without structures

Full text field is broken on add single. 

*** Full text field is broken. Click add single. Enter nothing in full text  click save  Will not save. Full text field box has error saying ‘Invalid string type, expected string’. If I add data and click save I get a 500 error.

What does ‘search my inventory items’ mean on front page?

On the top right dropdown: Report an issue could do with some explanation.

For invite user function in top right drop down: Explanation text should mention this utility is for EXTERNAL users (no webauth login).

When in Archive mode, there is an option still clone an entry which doesn’t feel right here.

Is search activities button in top of top relevant now?

*** On the clone single compound page, there is no escape or discontinue button that reverts to previous page

A re-evaluation of the top search bar is required in relation to assay reg and its usefulness for ChemiReg

In search page – What does archive mode actually mean / display? Explaination required

In search page – gallery mode is not required for inv projects

In search page – I click gallery mode. Clicking gallery mode again does not revert back to normal table

Excel and SDF export only provides the first 1000 rows. The button states ‘export ALL’. As such, it really needs to be the whole project.

Anywhere it says ‘add items via file’ does not make it clear that you can upload via SMILES and or InChIs

InChI submission needs re-evaluating. I don’t think it’s even working.

A-Z sorting in file upload page is not working as it should

There should not be an export option on the file upload page

Does the project page need a footer?

There is no link back the CBH website home page

An ‘About’ page is required to described the current version of software and any other spec details.

The FAQ page refers to an internal email address. Looking forward, do we need to change this to something that will not eventually get closed down?

*** Saved search is not saving my search parameters. Enter name of saved search and click save, nothing is saved.

Search page: clicking show advanced system / hide advanced system makes the button move around. 

In draw single: if I validate a structure I have drawn  enter new custom field information  click save  custom field information is not saved but structure is. If I enter the Custom field information before validating, works fine.

Substructure search really needs a loading bar while waiting

‘After fill down a message appears and it is possible to undo the changes just made’ : This is not working, clicking undo does nothing

It is not possible to sort by blanks

In search page : switching from gallery to list mode could be made clearer. I expect one button and for it to change appropriately depending on which view I’m in

‘Images can be rendered appropriately if labelled as an image link’ : I need this demoed to me

**Comment by aekhendry** [comment]
Continued:

‘ User can search by project data fields and the values they see are the most popular values in the data set that the current search is limitted to’ : Not certain what this means

I’m not convinced search by project data values is working as it should. As I’m not sure exactly how this should function, could Andy / Paul take a look.

Search by UOX ID is not returning any results. Doing so traps the system in an infinite loop, locking up the search page. I cut and paste the ID into the search bar, this is all I did differently.

On the project page, can we make the saved searches box look a little tidier, the text is too big for it.

‘substructure or smarts search is highlighted in the images’ This is not working for substructure or SMARTS

Searching, adding additional search terms and searching again is clunky. It might even be buggy. There are so many combinations possible I’m not sure where to start, but search definitely starts to slow/break down after multiple rounds of adding search terms to previous search results

Some of the buttons and general text on all pages need repositioning.

I can add an external user as an editor on a project via edit user roles. The External user does not have access to editing privileges despite being added as editor by the project owner. We need to be clear about what an external user can and can’t do here

‘password reset – if the password entered by a user is incorrect, the user gets a link to the password reset form, which works’: Currently the email you receive is a place holder, and the link it sends to change your password is not correct. This needs to be updated

‘a user can be invited, see the 4 scenarios outlined here: #679’  : This is a bit messy and I think could be a lot simpler. We just need one copy that invites an external user to a project. It doesn’t matter if it’s a reminder, it is just the same email. They follow the link to the sign up page. If they have already logged in (I.e. their user name already exists) then give them the opportunity to change their password. I think that is good enough. The messages that appear when inviting someone in the popup box can also be simplified correspondingly to – You have invited XXX to this/these project(s).

When using certain field types, it is apparent something is different but it is not clear what or why. For example, percentage filed has no % sign n the text box itself, tagging fields appear without warning as to what they are etc. Perhaps some revision here is required for a better user experience.

‘Should be possible to add uncurated fields’ : Only possible when drawing a compound, not when entering single inventoryreg item.

Info box on add multiple page, next to ‘drag and drop files here’. We do not really accept ChemDraw files. It would refer you to FAQ here.

Info box on add multiple page, next to ‘add multiple smiles or inchis here’ says user should get in contact for additional format upload. I think remove this as we won’t be able to do this now anyway.

‘Appropriate message for headers not retrieved’ : If I upload a file with no headers, it just lists them as unnamed. I’m not sure what the appropriate behavior is here?

‘Custom fields are validated and required fields are respected in this process’ : Required fields are NOT respected in this process.

Admin:

‘Custom field config can be compied and pasted to another copy of it’ :  I take this to mean you can copy and paste the schema which you cannot.

**Comment by KarenPorter** [comment]
@strets123 have all of the test items come from a wiki, pointed to in the application documentation?  In which case this can be closed in respect of latest hub release.

**Comment by KarenPorter** [comment]
OUtstanding effort - pull together into single version fior reference
